# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_choice_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
