# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_choice_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='select',
        ),
    ]
